runtime: go126

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_concurrent_requests: 80

handlers:
- url: /trading-calculator-groen-diap.svg
  static_files: trading-calculator-groen-diap.svg
  upload: trading-calculator-groen-diap.svg
  secure: always
  expiration: 365d

- url: /trading-calculator-rood-diap.svg
  static_files: trading-calculator-rood-diap.svg
  upload: trading-calculator-rood-diap.svg
  secure: always
  expiration: 365d

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always
  expiration: 365d

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  expiration: 365d

- url: /sitemap.txt
  static_files: sitemap.txt
  upload: sitemap.txt
  secure: always
  expiration: 365d

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  expiration: 365d
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    Cache-Control: "public, max-age=31536000, immutable"