runtime: go122

instance_class: F1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /sitemap.txt
  static_files: sitemap.txt
  upload: sitemap.txt
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets
  static_dir: assets
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
